# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tenjin < Formula
  desc "Tenjin is a CLI tool for automating learning data management from WaniKani."
  homepage "https://github.com/ajdexter/tenjin"
  version "0.3.1"

  depends_on "go"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ajdexter/tenjin/releases/download/v0.3.1/tenjin_Darwin_x86_64.tar.gz", using: GitHubPrivateRepositoryDownloadStrategy
      sha256 "2dd68b18e119007f77351f7b498a5891887a50df1403e75ae5d2d2ccad389893"

      def install
        bin.install "tenjin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ajdexter/tenjin/releases/download/v0.3.1/tenjin_Darwin_arm64.tar.gz", using: GitHubPrivateRepositoryDownloadStrategy
      sha256 "b6d50cd709d85a40d82938e97acd6e1fc9308be2dca80e74d2d0a77a7fff98b4"

      def install
        bin.install "tenjin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ajdexter/tenjin/releases/download/v0.3.1/tenjin_Linux_x86_64.tar.gz", using: GitHubPrivateRepositoryDownloadStrategy
        sha256 "4174698b196abc2465b222005c066961c62748001edf81b2fff46f7b53b59c42"

        def install
          bin.install "tenjin"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ajdexter/tenjin/releases/download/v0.3.1/tenjin_Linux_arm64.tar.gz", using: GitHubPrivateRepositoryDownloadStrategy
        sha256 "ec2a92133cedd84ef09763b8724e6ab8ec3dffc9c84501a417a7e16de6f0db8d"

        def install
          bin.install "tenjin"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Tenjin is provided for personal, non-commercial use only. Please ensure you comply with WaniKani's API terms of service.
    EOS
  end

  test do
    system "#{bin}/tenjin --version"
  end
end
