# This file was generated by GoReleaser. DO NOT EDIT.
cask "tenjin" do
  desc "A personal use command-line tool for managing WaniKani study materials and leeches."
  homepage "https://github.com/ajdexter/tenjin"
  version "0.3.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tenjin"
  depends_on formula: [
      "git",
    ]

  on_macos do
    on_intel do
      url "https://github.com/ajdexter/tenjin/releases/download/v0.3.2/tenjin_Darwin_x86_64.tar.gz"
      sha256 "b323654a840ae74e8932fb8ee8c1c68afaba22bd46a2b36ac69556e749afb2a8"
    end
    on_arm do
      url "https://github.com/ajdexter/tenjin/releases/download/v0.3.2/tenjin_Darwin_arm64.tar.gz"
      sha256 "f6e22286dbed8c1264ed3fc89466b273a0019c5f4c6515f80ad92e758f76351b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ajdexter/tenjin/releases/download/v0.3.2/tenjin_Linux_x86_64.tar.gz"
      sha256 "4c0e89fa0d88446ba1348e229984b821c5c1707ec1b7bba558c94cb69c1efe04"
    end
    on_arm do
      url "https://github.com/ajdexter/tenjin/releases/download/v0.3.2/tenjin_Linux_arm64.tar.gz"
      sha256 "0106d9be992fa2bbb4039852c96e44ced7a483eee1f706bf0a306813230b20da"
    end
  end

  caveats do
    "To get started, run:"
    "  tenjin --help"
    ""
    "For WaniKani integration, you'll need an API token from:"
    "  https://www.wanikani.com/settings/personal_access_tokens"
  end

  # No zap stanza required
end
